[package]
name = "axi-ide"
version = "1.0.0"
description = "Axi IDE FOSS Edition"
authors = ["The Ethos Project"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = ["api-all"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
libloading = "0.8" # Used for dynamically loading the axi_compiler.dll
