<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>avm</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.Input" Version="2.23.0" />
    <PackageReference Include="Silk.NET.OpenGL" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Windowing" Version="2.23.0" />
    <PackageReference Include="StbTrueTypeSharp" Version="1.26.13" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="SpatialStudio.RenderKit">
      <HintPath>C:\Ethos\allos\allos-ui\SpatialStudio.RenderKit\bin\Release\net10.0\SpatialStudio.RenderKit.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="JetBrainsMono-Regular.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
