#include "emitter.h"
#include <iostream>

namespace axiom {
namespace compiler {

void C23Emitter::indent() {
    for (int i = 0; i < indent_level; ++i) {
        out << "    ";
    }
}

std::string C23Emitter::emit(std::shared_ptr<ModuleNode> module) {
    out << "// Auto-generated by Axiom C23 Emitter\n";
    out << "#include <stdio.h>\n";
    out << "#include <stdint.h>\n\n";
    
    // We assume there's a main function or we wrap global statements in main
    // For now, let's emit them as functions or directly depending on AST
    
    for (const auto& stmt : module->items) {
        emitStatement(stmt);
    }
    
    return out.str();
}

void C23Emitter::emitStatement(std::shared_ptr<StmtNode> stmt) {
    if (auto imp = std::dynamic_pointer_cast<ImportNode>(stmt)) {
        std::string path = imp->module_path;
        size_t pos = 0;
        while ((pos = path.find("::", pos)) != std::string::npos) {
            path.replace(pos, 2, "/");
            pos += 1;
        }
        // Assume native headers are suffixed with _native.h for FOSS bindings
        out << "#include \"" << path << "_native.h\"\n";
    }
    else if (auto exprStmt = std::dynamic_pointer_cast<ExprStmt>(stmt)) {
        indent();
        emitExpression(exprStmt->expr);
        out << ";\n";
    }
    else if (auto fnDecl = std::dynamic_pointer_cast<FnDecl>(stmt)) {
        out << "\nint " << fnDecl->name << "() ";
        emitBlock(fnDecl->body);
        out << "\n";
    } 
    else if (auto assign = std::dynamic_pointer_cast<AssignStmt>(stmt)) {
        indent();
        // If target is an identifier, we might be declaring it
        // A robust C emitter would separate declarations from assignments
        // For simplicity in our demo, we'll try to guess based on if we are declaring
        if (auto ident = std::dynamic_pointer_cast<IdentNode>(assign->target)) {
            bool is_declared = false;
            for (const auto& var : declared_vars) {
                if (var == ident->name) { is_declared = true; break; }
            }
            if (!is_declared) {
                std::string c_type = assign->expr->resolved_type;
                if (c_type == "i32") c_type = "int32_t";
                else if (c_type == "f32") c_type = "float";
                else if (c_type == "str") c_type = "const char*";
                else c_type = assign->expr->resolved_type; // struct name
                out << c_type << " " << ident->name << " = ";
                declared_vars.push_back(ident->name);
            } else {
                out << ident->name << " = ";
            }
        } else {
            // For member access or reassignment, don't output type.
            emitExpression(assign->target);
            out << " = ";
        }
        emitExpression(assign->expr);
        out << ";\n";
    }
    else if (auto write = std::dynamic_pointer_cast<WriteStmt>(stmt)) {
        indent();
        out << "printf(\"%d\\n\", "; // TODO: format specifier based on type
        emitExpression(write->expr);
        out << ");\n";
    }
    else if (auto whileStmt = std::dynamic_pointer_cast<WhileStmt>(stmt)) {
        indent();
        out << "while (";
        emitExpression(whileStmt->condition);
        out << ") ";
        emitBlock(whileStmt->body);
        out << "\n";
    }
    else if (auto forStmt = std::dynamic_pointer_cast<ForStmt>(stmt)) {
        indent();
        out << "for (int32_t " << forStmt->iterator_name << " = 0; " << forStmt->iterator_name << " < ";
        emitExpression(forStmt->range);
        out << "; ++" << forStmt->iterator_name << ") ";
        emitBlock(forStmt->body);
        out << "\n";
    }
    else if (auto sdecl = std::dynamic_pointer_cast<StructDeclNode>(stmt)) {
        out << "typedef struct {\n";
        for (const auto& field : sdecl->fields) {
            std::string f_type = field.second;
            if (f_type == "i32") f_type = "int32_t";
            else if (f_type == "f32") f_type = "float";
            else if (f_type == "str") f_type = "const char*";
            out << "    " << f_type << " " << field.first << ";\n";
        }
        out << "} " << sdecl->name << ";\n\n";
    }
    else if (auto nd = std::dynamic_pointer_cast<NativeFnDeclNode>(stmt)) {
        // We emit the C declaration so it can be linked
        std::string c_ret = nd->return_type;
        if (c_ret == "i32") c_ret = "int32_t";
        else if (c_ret == "f32") c_ret = "float";
        else if (c_ret == "str") c_ret = "const char*";
        
        out << "extern " << c_ret << " " << nd->name << "(";
        for (size_t i = 0; i < nd->params.size(); ++i) {
            std::string p_type = nd->params[i].second;
            if (p_type == "i32") p_type = "int32_t";
            else if (p_type == "f32") p_type = "float";
            else if (p_type == "str") p_type = "const char*";
            out << p_type << " " << nd->params[i].first;
            if (i < nd->params.size() - 1) out << ", ";
        }
        out << ");\n\n";
    }
}

void C23Emitter::emitBlock(std::shared_ptr<BlockStmt> block) {
    out << "{\n";
    indent_level++;
    for (const auto& stmt : block->statements) {
        emitStatement(stmt);
    }
    indent_level--;
    indent();
    out << "}";
}

void C23Emitter::emitExpression(std::shared_ptr<ExprNode> expr) {
    if (auto lit = std::dynamic_pointer_cast<LiteralNode>(expr)) {
        if (lit->resolved_type == "str") out << "\"" << lit->value << "\"";
        else out << lit->value;
    }
    else if (auto ident = std::dynamic_pointer_cast<IdentNode>(expr)) {
        out << ident->name;
    }
    else if (auto bin = std::dynamic_pointer_cast<BinaryNode>(expr)) {
        out << "(";
        emitExpression(bin->lhs);
        out << " " << bin->op << " ";
        emitExpression(bin->rhs);
        out << ")";
    }
    else if (auto sinit = std::dynamic_pointer_cast<StructInitNode>(expr)) {
        out << "(" << sinit->struct_name << "){";
        for (size_t i = 0; i < sinit->fields.size(); ++i) {
            out << "." << sinit->fields[i].first << " = ";
            emitExpression(sinit->fields[i].second);
            if (i < sinit->fields.size() - 1) out << ", ";
        }
        out << "}";
    }
    else if (auto idx = std::dynamic_pointer_cast<IndexNode>(expr)) {
        emitExpression(idx->object);
        out << "[";
        emitExpression(idx->index);
        out << "]";
    }
    else if (auto macc = std::dynamic_pointer_cast<MemberAccessNode>(expr)) {
        emitExpression(macc->object);
        out << "." << macc->member;
    }
    else if (auto fncall = std::dynamic_pointer_cast<FnCallNode>(expr)) {
        out << fncall->name << "(";
        for (size_t i = 0; i < fncall->args.size(); ++i) {
            emitExpression(fncall->args[i]);
            if (i < fncall->args.size() - 1) out << ", ";
        }
        out << ")";
    }
}

} // namespace compiler
} // namespace axiom
